Exercise 1

In [1]:
import numpy as np
ab=np.array([[1500,3000,5000]])
print(ab)


[[1500 3000 5000]]


In [2]:
abc=np.array([
    
    [10,15,8,12],
    [5,7,4,6],
    [2,3,2,4]
])
print(abc)

[[10 15  8 12]
 [ 5  7  4  6]
 [ 2  3  2  4]]
